# Generated by Django 2.0.5 on 2018-05-08 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='descrición'),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.TextField(verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.TextField(verbose_name='ligazón'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(verbose_name='localización'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='estado'),
        ),
    ]
