# Generated by Django 2.0.5 on 2018-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180508_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_published',
            field=models.BooleanField(default=False, verbose_name='google_cal_published'),
        ),
    ]
