# Generated by Django 2.0.5 on 2018-05-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_google_calendar_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.TextField(null=True, verbose_name='google event id'),
        ),
    ]
