# Generated by Django 2.0.5 on 2018-05-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(null=True, verbose_name='title'),
        ),
    ]
