# Generated by Django 2.0.5 on 2018-06-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_event_htmllink',
            field=models.TextField(null=True, verbose_name='google event link'),
        ),
    ]
