# Generated by Django 2.1.2 on 2018-11-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_google_event_htmllink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
