# Generated by Django 2.1.2 on 2018-11-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='import_id',
            field=models.TextField(null=True, verbose_name='import event id'),
        ),
    ]
