# Generated by Django 2.1.2 on 2018-11-21 21:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_import_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='nome')),
                ('logo', models.TextField(verbose_name='logo')),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='links')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
